name: issue translator
#event 
on:
  issue:
     types: [opend]
  issue_comment:
     types: [created]
# job
jobs:
  bluid:
  #runners
   runs-on: ubuntu-latest
# steps
  steps: 
      # action  -> maketplace "Issues Translate Action"
     - uses: usthe/issues-translate-action@v2.7
