name: Issues Translator
#event 
on: 
  issue_comment: 
    types: [created]
  issues: 
    types: [opened]
# job
jobs:
  build:
   #runners
    runs-on: ubuntu-latest
      # steps  
    steps:
       # action  -> maketplace "Issues Translate Action"
      - uses: dromara/issues-translate-action@v2.7

